version: '3.7'

services:
  web:
    container_name: flask
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/docker_imse_m2_group6
    depends_on:
      - db
      - mongodb

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: sql
    environment:
      MYSQL_DATABASE: sql_imse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-datavolume:/var/lib/mysql
    expose:
      - 8008

  mongodb:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo_imse
    expose:
      - 27017

volumes:
  my-datavolume:
